# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20171119_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
    ]
